#!/bin/sh

rm -rf 0

rm -rf constant/polyMesh

rm -rf constant/fluid/polyMesh

rm -rf constant/solid/polyMesh

rm -rf dynamicCode

rm -rf VTK

rm -rf *.csv

rm -rf log.*

rm -rf 0.0*

rm -rf *-*

rm -rf postProcessing/fluid

rm -rf postProcessing/interface/*

rm -rf postProcessing/processed_interface
